name              'yum-ius'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures the IUS Community Project Yum Repository'
version           '3.2.15'
source_url        'https://github.com/sous-chefs/yum-ius'
issues_url        'https://github.com/sous-chefs/yum-ius/issues'
chef_version      '>= 15.3'

depends 'yum-epel'

supports 'centos', '~> 7.0'
supports 'oracle', '~> 7.0'
supports 'redhat', '~> 7.0'
supports 'scientific', '~> 7.0'
