---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@6.0.0

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos-7
          - oraclelinux-7
        suite:
          - default
          - enable-all
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Cinc Workstation
        uses: sous-chefs/.github/.github/actions/install-workstation@6.0.0
      - name: Run Test Kitchen
        uses: actionshub/test-kitchen@3.0.0
        env:
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
